using System.Diagnostics.CodeAnalysis;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators.MqttSubscriptions;

[SuppressMessage("Design", "CA1052:Static holder types should be Static or NotInheritable", Justification = "Intentional base class for incremental generators.")]
public class GeneratorInternal
{
    private const string Namespace = "MqttSubscriptions";
    private const string AttributeName = "MqttSubscription";

    protected sealed class MqttSubscriptionGenerationTarget
    {
        public string Topic { get; }
        public INamedTypeSymbol ClassSymbol { get; }
        public MqttSubscriptionGenerationTarget(INamedTypeSymbol classSymbol, string topic)
        {
            Topic = topic;
            ClassSymbol = classSymbol;
        }
    }

    protected GeneratorInternal() { }

    protected static void CreateAttribute(IncrementalGeneratorInitializationContext context)
    {
        var projectNamespaceProvider = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) =>
            {
                ///if (options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace) &&
                ///    !string.IsNullOrWhiteSpace(rootNamespace))
                ///{
                ///    return rootNamespace;
                ///}

                if (options.GlobalOptions.TryGetValue("build_property.MSBuildProjectName", out var projectName) &&
                    !string.IsNullOrWhiteSpace(projectName))
                {
                    return projectName;
                }

                return string.Empty;
            });

        var attributeNamespaceProvider = context.CompilationProvider
            .Combine(projectNamespaceProvider)
            .Select(static (data, _) =>
                string.IsNullOrWhiteSpace(data.Right)
                    ? data.Left.AssemblyName ?? Namespace
                    : data.Right);

        context.RegisterSourceOutput(attributeNamespaceProvider, static (ctx, attributeNamespace) =>
            ctx.AddSource($"{AttributeName}.g.cs", SourceText.From(GetAttributeFile(attributeNamespace), Encoding.UTF8)));
    }

    private static string GetAttributeFile(string attributeNamespace) => $$"""
        // <auto-generated />

        namespace {{attributeNamespace}}.{{Namespace}};

        [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        #pragma warning disable CS9113 // Parameter is unread.
        public sealed class {{AttributeName}}(string Topic) : System.Attribute {}
        #pragma warning restore CS9113 // Parameter is unread.
        """;

    protected static bool IsCandidate(SyntaxNode node) =>
        node is
            ClassDeclarationSyntax { AttributeLists.Count: > 0 } or
            RecordDeclarationSyntax { AttributeLists.Count: > 0 };

    /// <summary>
    /// Symbol and MQTT topic resolved while semantic model is available (attribute data alone can be empty for source-generated attributes).
    /// </summary>
    protected static MqttSubscriptionGenerationTarget? GetMqttGenerationTarget(GeneratorSyntaxContext context)
    {
        if (context.Node is not TypeDeclarationSyntax typeDecl)
            return null;

        if (context.SemanticModel.GetDeclaredSymbol(typeDecl) is not INamedTypeSymbol symbol)
            return null;

        if (symbol.TypeKind is not TypeKind.Class)
            return null;

        if (symbol.DeclaredAccessibility is not Accessibility.Public)
            return null;

        if (!symbol.IsSealed)
            return null;

        if (!HasTargetAttribute(symbol))
            return null;

        var topic = GetMqttSubscriptionTopic(symbol)
            ?? ExtractTopicFromAttributeSyntax(context.SemanticModel, typeDecl)
            ?? string.Empty;

        return new MqttSubscriptionGenerationTarget(symbol, topic);
    }

    private static bool HasTargetAttribute(INamedTypeSymbol symbol) =>
        symbol.GetAttributes()
            .Any(a => IsMqttSubscriptionAttributeName(a.AttributeClass?.Name));

    private static bool IsMqttSubscriptionAttributeName(string? attributeClassName) =>
        string.Equals(attributeClassName, AttributeName, StringComparison.Ordinal);

    /// <summary>
    /// Topic from <c>[MqttSubscription(Topic)]</c> constructor or named member, if present.
    /// </summary>
    protected static string? GetMqttSubscriptionTopic(INamedTypeSymbol symbol)
    {
        foreach (var attr in symbol.GetAttributes())
        {
            if (!IsMqttSubscriptionAttributeName(attr.AttributeClass?.Name))
                continue;

            foreach (var arg in attr.ConstructorArguments)
            {
                var s = StringFromTypedConstant(arg);
                if (s is not null)
                    return s;
            }

            foreach (var named in attr.NamedArguments)
            {
                if (!string.Equals(named.Key, "Topic", StringComparison.Ordinal))
                    continue;
                var s = StringFromTypedConstant(named.Value);
                if (s is not null)
                    return s;
            }
        }

        return null;
    }

    private static string? StringFromTypedConstant(TypedConstant arg)
    {
        if (arg.Kind == TypedConstantKind.Error)
            return null;

        if (arg.IsNull)
            return null;

        return arg.Value as string;
    }

    private static string? ExtractTopicFromAttributeSyntax(SemanticModel model, TypeDeclarationSyntax typeDecl)
    {
        foreach (var attrList in typeDecl.AttributeLists)
        {
            foreach (var attr in attrList.Attributes)
            {
                if (!IsMqttSubscriptionAttributeSyntax(model, attr))
                    continue;

                if (attr.ArgumentList?.Arguments is not { Count: > 0 } args)
                    continue;

                var c = model.GetConstantValue(args[0].Expression);
                if (c.HasValue && c.Value is string s)
                    return s;
            }
        }

        return null;
    }

    private static bool IsMqttSubscriptionAttributeSyntax(SemanticModel model, AttributeSyntax attr) =>
        model.GetSymbolInfo(attr).Symbol is IMethodSymbol ctor
            ? IsMqttSubscriptionAttributeName(ctor.ContainingType?.Name)
            : IsMqttSubscriptionAttributeName(GetAttributeSimpleName(attr.Name));


    private static string? GetAttributeSimpleName(NameSyntax name) =>
        name switch
        {
            IdentifierNameSyntax id => id.Identifier.Text,
            GenericNameSyntax g => g.Identifier.Text,
            QualifiedNameSyntax q => q.Right switch
            {
                IdentifierNameSyntax id2 => id2.Identifier.Text,
                GenericNameSyntax g2 => g2.Identifier.Text,
                _ => null,
            },
            AliasQualifiedNameSyntax a => a.Name switch
            {
                IdentifierNameSyntax id3 => id3.Identifier.Text,
                GenericNameSyntax g3 => g3.Identifier.Text,
                _ => null,
            },
            _ => null,
        };
}
