using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators.MqttSubscriptions;

[Generator]
public sealed class MqttSubscriptionsGenerator : GeneratorInternal, IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Create attribute
        CreateAttribute(context);

        // Find all class declarations with attribute
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidate(s), // quick filter
                transform: static (ctx, _) => GetMqttGenerationTarget(ctx))
            .Where(static m => m is not null)!;

        // Generate code for each matched class
        context.RegisterSourceOutput(classDeclarations, static (spc, target) =>
            GenerateSerializer(spc, target!));
    }

#pragma warning disable MA0051 // Method is too long
    private static void GenerateSerializer(SourceProductionContext context, MqttSubscriptionGenerationTarget target)
#pragma warning restore MA0051 // Method is too long
    {
        var classSymbol = target.ClassSymbol;
        var @namespace = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : classSymbol.ContainingNamespace.ToDisplayString();

        var className = classSymbol.Name
            .Replace("Command", "MqttSubscription");

        var topicLiteral = SyntaxFactory.Literal(target.Topic).Text;

        var sb = new StringBuilder()
            .AppendLine("// <auto-generated>")
            .AppendLine()
            .AppendLine("using Aspu.Common.Application.Abstractions.Mqtt;")
            .AppendLine("using Mediator;")
            .AppendLine("using Microsoft.Extensions.Logging;")
            .AppendLine("using System.Diagnostics;")
            .AppendLine("using System.Diagnostics.CodeAnalysis;")
            .AppendLine("using System.Text.Json;")
            .AppendLine();

        if (!string.IsNullOrEmpty(@namespace))
            sb.Append("namespace ").Append(@namespace).AppendLine(";").AppendLine();

        sb.Append("public class ").Append(className).AppendLine("(")
            .AppendLine("    IMediator mediator,")
            .Append("    ILogger<").Append(className).AppendLine("> logger)")
            .AppendLine("    : IMqttMessageHandler")
            .AppendLine("{")
            .Append("    public string Topic => ").Append(topicLiteral).AppendLine(";")
            .AppendLine()
            .AppendLine("    public async Task HandleAsync(string topic, ReadOnlyMemory<byte> payload, CancellationToken cancellationToken)")
            .AppendLine("    {")
            .AppendLine("        var startTime = Stopwatch.GetTimestamp();")
            .AppendLine()
            .Append("        var command = JsonSerializer.Deserialize<").Append(classSymbol.Name).AppendLine(">(payload.Span);")
            .AppendLine("        if (command is null)")
            .AppendLine("            return;")
            .AppendLine()
            .AppendLine("        await mediator.Send(command, cancellationToken);")
            .AppendLine("        var elapsedTime = Stopwatch.GetElapsedTime(startTime);")
            .AppendLine()
            .AppendLine("        if (logger.IsEnabled(LogLevel.Information))")
            .AppendLine("            logger.LogInformation(\"Mqtt publication on {@Topic} {@Total} ms\", topic, elapsedTime.TotalMilliseconds);")
            .AppendLine("    }")
            .AppendLine("}");

        context.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
