services:
  aspu.api:
    image: ${DOCKER_REGISTRY-}aspuapi
    container_name: aspu.api
    build:
      context: .
      dockerfile: source/API/Aspu.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    depends_on:
      - mosquitto

  aspu.gateway:
    image: ${DOCKER_REGISTRY-}aspugateway
    container_name: aspu.gateway
    build:
      context: .
      dockerfile: source/API/Aspu.Gateway/Dockerfile
    ports:
      - 3000:8080
      - 3001:8081

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
