using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators.Domain;

public class GeneratorInternal<TGenerator>
    where TGenerator : IIncrementalGenerator, new()
{
    private static Type Type => typeof(TGenerator);
    private static string Namespace => Type.Namespace;
    private static string AttributeName => Type.Name.Replace("Generator", "Attribute");

    protected GeneratorInternal() { }

    protected static void CreateAttribute(IncrementalGeneratorInitializationContext context)
    {
        var projectNamespaceProvider = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) =>
            {
                ///if (options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace) &&
                ///    !string.IsNullOrWhiteSpace(rootNamespace))
                ///{
                ///    return rootNamespace;
                ///}

                if (options.GlobalOptions.TryGetValue("build_property.MSBuildProjectName", out var projectName) &&
                    !string.IsNullOrWhiteSpace(projectName))
                {
                    return projectName;
                }

                return string.Empty;
            });

        var attributeNamespaceProvider = context.CompilationProvider
            .Combine(projectNamespaceProvider)
            .Select(static (data, _) =>
                string.IsNullOrWhiteSpace(data.Right)
                    ? data.Left.AssemblyName ?? Namespace
                    : data.Right);

        context.RegisterSourceOutput(attributeNamespaceProvider, static (ctx, attributeNamespace) =>
            ctx.AddSource($"{AttributeName}.g.cs", SourceText.From(GetAttributeFile(attributeNamespace), Encoding.UTF8)));
    }

    private static string GetAttributeFile(string attributeNamespace) => $$"""
        // <auto-generated />

        namespace {{attributeNamespace.Replace(".Domain", string.Empty)}}.{{Namespace}};

        [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        public sealed class {{AttributeName}} : System.Attribute {}
        """;

    protected static bool IsCandidate(SyntaxNode node) =>
        node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0;

    protected static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
            return null;

        if (symbol.TypeKind is not TypeKind.Class)
            return null;

        if (symbol.DeclaredAccessibility is not Accessibility.Public)
            return null;

        if (!symbol.IsSealed)
            return null;

        return HasTargetAttribute(symbol) ? symbol : null;
    }

    private static bool HasTargetAttribute(INamedTypeSymbol symbol) =>
        symbol.GetAttributes()
            .Any(static attribute =>
                string.Equals(attribute.AttributeClass?.Name, AttributeName, StringComparison.Ordinal) ||
                string.Equals(attribute.AttributeClass?.Name, AttributeName.Replace("Attribute", string.Empty), StringComparison.Ordinal));
}
