using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators.Validators;

[Generator]
public sealed class ValidatorRegistrationGenerator : IIncrementalGenerator
{
    private const string InterfaceName = "IValidator";
    private const string BaseClassName = "FluentValidation.AbstractValidator`1";

    private static string Namespace => typeof(ValidatorRegistrationGenerator).Namespace;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ///if (!Debugger.IsAttached)
        ///    Debugger.Launch();

        var classDeclarations = context.SyntaxProvider
         .CreateSyntaxProvider(
             predicate: static (s, _) => IsCandidate(s), // quick filter
             transform: static (ctx, _) => GetSemanticTarget(ctx)) // get symbol
         .Where(static m => m is not null)!;

        var collectedClasses = classDeclarations.Collect();
        var compilationProvider = context.CompilationProvider;
        var combined = compilationProvider.Combine(collectedClasses);

        context.RegisterSourceOutput(combined, static (spc, classSymbols) => Generate(spc, classSymbols!));
    }

    private static bool IsCandidate(SyntaxNode node) =>
        node is ClassDeclarationSyntax cds && cds.BaseList is not null;

    private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
            return null;

        if (symbol.TypeKind is not TypeKind.Class)
            return null;

        if (symbol.DeclaredAccessibility is not Accessibility.Internal)
            return null;

        if (!symbol.IsSealed)
            return null;

        return symbol.AllInterfaces.Any(a =>
            string.Equals(a.Name, InterfaceName, StringComparison.Ordinal))
                ? symbol : null;
    }

    private static void Generate(SourceProductionContext context, (Compilation compilation, ImmutableArray<INamedTypeSymbol?> classes) data)
    {
        var (compilation, classSymbols) = data;

        if (classSymbols.IsDefaultOrEmpty)
            return;

        var assemblyName = compilation.AssemblyName;
        var abstractValidatorSymbol = compilation.GetTypeByMetadataName(BaseClassName);

        var sb = new StringBuilder(4096)
            .AppendLine("// <auto-generated>")
            .AppendLine();

        var namespaces = classSymbols
            .Where(x => x is not null)
            .Select(x => x!.ContainingNamespace)
            .Where(x => !x.IsGlobalNamespace)
            .Select(x => x.ToDisplayString())
            .ToList();
        namespaces.AddRange([
            "Microsoft.Extensions.DependencyInjection",
            "FluentValidation",
        ]);
        foreach (var @namespace in namespaces.OrderBy(x => x, StringComparer.Ordinal).Distinct(StringComparer.Ordinal))
            sb.Append("using ").Append(@namespace).Append(';').AppendLine();
        sb.AppendLine();

        sb.Append("namespace ").Append(assemblyName).Append('.').Append(Namespace).Append(';').AppendLine();
        sb.AppendLine();
        sb.AppendLine("public static class ValidatorRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddValidators(this IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var classSymbol in classSymbols
            .Where(x => x is not null)
            .OrderBy(x => x!.Name, StringComparer.Ordinal))
        {
            var baseClassSymbol = FindBaseClass(classSymbol, abstractValidatorSymbol);
            var modelTypeName = baseClassSymbol?.TypeArguments[0]?.ToDisplayString();
            if (string.IsNullOrWhiteSpace(modelTypeName))
                continue;

            sb.Append("        services.AddScoped<").Append(InterfaceName).Append('<').Append(modelTypeName).Append(">, ").Append(classSymbol!.Name).AppendLine(">();");
        }
        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        context.AddSource("ValidatorRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static INamedTypeSymbol? FindBaseClass(INamedTypeSymbol? symbol, INamedTypeSymbol? baseClassSymbol)
    {
        var baseType = symbol?.BaseType;
        return baseType is null ||
            baseClassSymbol is null ||
            !SymbolEqualityComparer.Default.Equals(baseType.OriginalDefinition, baseClassSymbol)
            ? null
            : baseType;
    }
}
