using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators.Endpoints;

[Generator]
public sealed class EndpointsRegistrationGenerator : IIncrementalGenerator
{
    private const string InterfaceName = "IEndpoint";
    private const string IEndpointMetadataName = "Aspu.Common.Presentation.Endpoints.IEndpoint";
    private static readonly DiagnosticDescriptor InaccessibleReferencedEndpoint = new(
        id: "SGE001",
        title: "Referenced endpoint is not accessible",
        messageFormat: "Endpoint type '{0}' from assembly '{1}' implements IEndpoint but is not accessible from '{2}'. Make it public or expose it explicitly.",
        category: "SourceGenerators.Endpoints",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static string Namespace => typeof(EndpointsRegistrationGenerator).Namespace;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ///if (!Debugger.IsAttached)
        ///    Debugger.Launch();

        context.RegisterSourceOutput(
            context.CompilationProvider,
            static (spc, compilation) => Generate(spc, compilation));
    }

#pragma warning disable MA0051 // Method is too long
    private static void Generate(SourceProductionContext context, Compilation compilation)
#pragma warning restore MA0051 // Method is too long
    {
        var interfaceSymbol = compilation.GetTypeByMetadataName(IEndpointMetadataName) ?? FindInterface(compilation, InterfaceName);
        if (interfaceSymbol is null)
            return;

        var discoveryResult = GetEndpointTypes(compilation, interfaceSymbol);
        foreach (var skippedEndpoint in discoveryResult.InaccessibleReferencedEndpoints)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                InaccessibleReferencedEndpoint,
                Location.None,
                skippedEndpoint.ToDisplayString(),
                skippedEndpoint.ContainingAssembly.Name,
                compilation.AssemblyName));
        }

        var endpointTypes = discoveryResult.AccessibleEndpoints;
        if (endpointTypes.IsDefaultOrEmpty)
            return;

        var interfaceNamespace = interfaceSymbol.ContainingNamespace.IsGlobalNamespace
            ? "Aspu.Common.Presentation.Endpoints"
            : interfaceSymbol.ContainingNamespace.ToDisplayString();

        var sb = new StringBuilder(4096)
            .AppendLine("// <auto-generated>")
            .AppendLine();

        sb.Append("using ").Append(interfaceNamespace).Append(';').AppendLine();
        sb.Append("using ").Append("System.Globalization").Append(';').AppendLine();
        sb.Append("using ").Append("Microsoft.AspNetCore.Builder").Append(';').AppendLine();
        sb.Append("using ").Append("Microsoft.AspNetCore.Http").Append(';').AppendLine();
        sb.Append("using ").Append("Microsoft.AspNetCore.Routing").Append(';').AppendLine();
        sb.AppendLine();
        sb.Append("namespace ").Append(compilation.AssemblyName).Append('.').Append(Namespace).Append(';').AppendLine();
        sb.AppendLine();
        sb.AppendLine("internal static class EndpointsRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static IEndpointRouteBuilder MapEndpoints(");
        sb.AppendLine("        IEndpointRouteBuilder app,");
        sb.AppendLine("        RouteGroupBuilder routeGroupBuilder = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        var builder = routeGroupBuilder ?? app;");
        sb.AppendLine();
        foreach (var endpointType in endpointTypes)
            sb.Append("        MapEndpoints(new ").Append(GetQualifiedTypeName(endpointType)).AppendLine("(), builder);");
        sb.AppendLine();
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static IEndpointRouteBuilder MapEndpoints(");
        sb.AppendLine("        IEndpoint module,");
        sb.AppendLine("        IEndpointRouteBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        var group = string.IsNullOrWhiteSpace(module.Tags)");
        sb.AppendLine("            ? builder");
        sb.AppendLine("            : builder");
        sb.AppendLine("                .MapGroup(GetGroup(module.Tags))");
        sb.AppendLine("                .WithTags(GetTags(module.Tags));");
        sb.AppendLine("        module.MapEndpoint(group);");
        sb.AppendLine("        return group;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static string GetTags(string input) =>");
        sb.AppendLine("        string.IsNullOrWhiteSpace(input)");
        sb.AppendLine("            ? input");
        sb.AppendLine("            : string.Create(input.Length, input, (span, src) =>");
        sb.AppendLine("            {");
        sb.AppendLine("                span[0] = char.ToUpperInvariant(src[0]);");
        sb.AppendLine("                for (var i = 1; i < src.Length; i++)");
        sb.AppendLine("                    span[i] = char.ToLowerInvariant(src[i]);");
        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine("    private static string GetGroup(string input) =>");
        sb.AppendLine("        string.IsNullOrWhiteSpace(input)");
        sb.AppendLine("            ? input");
        sb.AppendLine("            : $\"/{input.ToLower(CultureInfo.InvariantCulture)}\";");
        sb.AppendLine("}");
        context.AddSource("EndpointsRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static EndpointDiscoveryResult GetEndpointTypes(Compilation compilation, INamedTypeSymbol interfaceSymbol)
    {
        var currentAssembly = compilation.Assembly;
        var endpointTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        var inaccessibleReferencedEndpoints = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        CollectEndpointTypes(currentAssembly.GlobalNamespace, interfaceSymbol, currentAssembly, endpointTypes, inaccessibleReferencedEndpoints);

        foreach (var reference in compilation.References)
        {
            var referencedAssembly = compilation.GetAssemblyOrModuleSymbol(reference) switch
            {
                IAssemblySymbol assembly => assembly,
                IModuleSymbol module => module.ContainingAssembly,
                _ => null,
            };

            if (referencedAssembly is null)
                continue;

            CollectEndpointTypes(referencedAssembly.GlobalNamespace, interfaceSymbol, currentAssembly, endpointTypes, inaccessibleReferencedEndpoints);
        }

        return new EndpointDiscoveryResult(
            endpointTypes
                .OrderBy(static symbol => symbol.ToDisplayString(), StringComparer.Ordinal)
                .ToImmutableArray(),
            inaccessibleReferencedEndpoints
                .OrderBy(static symbol => symbol.ToDisplayString(), StringComparer.Ordinal)
                .ToImmutableArray());
    }

    private static void CollectEndpointTypes(
        INamespaceSymbol @namespace,
        INamedTypeSymbol interfaceSymbol,
        IAssemblySymbol currentAssembly,
        ISet<INamedTypeSymbol> endpointTypes,
        ISet<INamedTypeSymbol> inaccessibleReferencedEndpoints)
    {
        foreach (var type in @namespace.GetTypeMembers())
            CollectEndpointTypes(type, interfaceSymbol, currentAssembly, endpointTypes, inaccessibleReferencedEndpoints);

        foreach (var childNamespace in @namespace.GetNamespaceMembers())
            CollectEndpointTypes(childNamespace, interfaceSymbol, currentAssembly, endpointTypes, inaccessibleReferencedEndpoints);
    }

    private static void CollectEndpointTypes(
        INamedTypeSymbol type,
        INamedTypeSymbol interfaceSymbol,
        IAssemblySymbol currentAssembly,
        ISet<INamedTypeSymbol> endpointTypes,
        ISet<INamedTypeSymbol> inaccessibleReferencedEndpoints)
    {
        switch (GetEndpointDiscoveryState(type, interfaceSymbol, currentAssembly))
        {
            case EndpointDiscoveryState.Accessible:
                endpointTypes.Add(type);
                break;
            case EndpointDiscoveryState.InaccessibleReferenced:
                inaccessibleReferencedEndpoints.Add(type);
                break;
        }

        foreach (var childType in type.GetTypeMembers())
            CollectEndpointTypes(childType, interfaceSymbol, currentAssembly, endpointTypes, inaccessibleReferencedEndpoints);
    }

    private static EndpointDiscoveryState GetEndpointDiscoveryState(
        INamedTypeSymbol symbol,
        INamedTypeSymbol interfaceSymbol,
        IAssemblySymbol currentAssembly)
    {
        if (symbol.TypeKind is not TypeKind.Class || symbol.IsAbstract || !symbol.IsSealed)
            return EndpointDiscoveryState.NotEndpoint;

        if (!symbol.AllInterfaces.Any(interfaceImplementation =>
            SymbolEqualityComparer.Default.Equals(interfaceImplementation, interfaceSymbol)))
            return EndpointDiscoveryState.NotEndpoint;

        if (IsAccessibleFromCompilation(symbol, currentAssembly))
            return EndpointDiscoveryState.Accessible;

        return SymbolEqualityComparer.Default.Equals(symbol.ContainingAssembly, currentAssembly)
            ? EndpointDiscoveryState.NotEndpoint
            : EndpointDiscoveryState.InaccessibleReferenced;
    }

    private static bool IsAccessibleFromCompilation(INamedTypeSymbol symbol, IAssemblySymbol currentAssembly) =>
        SymbolEqualityComparer.Default.Equals(symbol.ContainingAssembly, currentAssembly)
            ? symbol.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal
            : IsPubliclyAccessible(symbol);

    private static bool IsPubliclyAccessible(INamedTypeSymbol symbol)
    {
        if (symbol.DeclaredAccessibility is not Accessibility.Public)
            return false;

        for (var containingType = symbol.ContainingType; containingType is not null; containingType = containingType.ContainingType)
        {
            if (containingType.DeclaredAccessibility is not Accessibility.Public)
                return false;
        }

        return true;
    }

    private static string GetQualifiedTypeName(INamedTypeSymbol symbol) =>
        symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private sealed class EndpointDiscoveryResult
    {
        public EndpointDiscoveryResult(
            ImmutableArray<INamedTypeSymbol> accessibleEndpoints,
            ImmutableArray<INamedTypeSymbol> inaccessibleReferencedEndpoints)
        {
            AccessibleEndpoints = accessibleEndpoints;
            InaccessibleReferencedEndpoints = inaccessibleReferencedEndpoints;
        }

        public ImmutableArray<INamedTypeSymbol> AccessibleEndpoints { get; }

        public ImmutableArray<INamedTypeSymbol> InaccessibleReferencedEndpoints { get; }
    }

    private enum EndpointDiscoveryState
    {
        NotEndpoint,
        Accessible,
        InaccessibleReferenced,
    }

    private static INamedTypeSymbol? FindInterface(Compilation compilation, string name) =>
        FindInNamespace(compilation.GlobalNamespace, name);

    private static INamedTypeSymbol? FindInNamespace(INamespaceSymbol ns, string name)
    {
        foreach (var member in ns.GetMembers())
        {
            if (member is INamespaceSymbol childNs)
            {
                var found = FindInNamespace(childNs, name);
                if (found is not null)
                    return found;

                continue;
            }

            if (member is INamedTypeSymbol type && type.TypeKind == TypeKind.Interface && string.Equals(type.Name, name, StringComparison.OrdinalIgnoreCase))
                return type;
        }

        return null;
    }
}
