using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators.Presentation;

/// <summary>
/// Generates <c>Add{Transport}Handlers</c>: per handler a keyed scoped registration (key = handler type) and
/// an <c>InboundProcessorTopic</c> with its constant <c>Topic</c>, so the runtime registry never instantiates handlers.
/// Transport generators only pass their handler interface and name.
/// </summary>
public abstract class BaseHandlersRegistrationGenerator(string interfaceName, string interfaceNamespace, string transport)
    : BaseRegistrationGenerator, IIncrementalGenerator
{
    private const string TopicPropertyName = "Topic";
    private const string InboundProcessorNamespace = "Aspu.Common.Presentation.Abstractions.InboundProcessor";

    private static readonly string Namespace = typeof(BaseHandlersRegistrationGenerator).Namespace;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // The transform runs for every candidate node, so it captures only the interface name, not the generator.
        var handlerInterface = interfaceName;

        var handlers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsHandlerCandidate(node),
                transform: (ctx, ct) => GetInboundHandlerTarget(ctx, handlerInterface, ct))
            .Where(static symbol => symbol is not null)
            .Collect();

        context.RegisterSourceOutput(context.CompilationProvider.Combine(handlers), Generate);
    }

    private void Generate(SourceProductionContext context, (Compilation Compilation, ImmutableArray<INamedTypeSymbol?> Handlers) data)
    {
        var (compilation, classSymbols) = data;
        if (classSymbols.IsDefaultOrEmpty)
            return;

        var source = GenerateString(context, compilation, classSymbols);
        context.AddSource($"{transport}HandlersRegistration.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private string GenerateString(SourceProductionContext context, Compilation compilation, ImmutableArray<INamedTypeSymbol?> classSymbols)
    {
        var handlerNamespace = GetNamespace(compilation, interfaceNamespace, interfaceName, $"{interfaceNamespace}.{interfaceName}");
        var assemblyName = compilation.AssemblyName!.Replace(".Presentation", string.Empty);

        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine();
        sb.Append(Using).Append(handlerNamespace).Append(';').AppendLine();
        sb.Append(Using).AppendLine("Microsoft.Extensions.DependencyInjection;");
        sb.Append(Using).AppendLine("Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.Append(Using).Append(InboundProcessorNamespace).Append(';').AppendLine();
        sb.AppendLine();
        sb.Append("namespace ").Append(assemblyName).Append('.').Append(Namespace).Append(';').AppendLine();
        sb.AppendLine();
        sb.Append("internal static class ").Append(transport).AppendLine("HandlersRegistration");
        sb.AppendLine("{");
        sb.Append("    public static IServiceCollection Add").Append(transport).AppendLine("Handlers(");
        sb.AppendLine("        this IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var (name, topic, symbol) in GetInboundHandlers(context, compilation, classSymbols))
        {
            if (!IsRegistrableHandler(symbol))
            {
                context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.NotRegistrableHandler, symbol.Locations.FirstOrDefault(), symbol.Name, interfaceName));
                continue;
            }

            if (IsGenericHandler(symbol))
            {
                context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.GenericHandler, symbol.Locations.FirstOrDefault(), symbol.Name, interfaceName));
                continue;
            }

            if (topic is null)
            {
                context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.NonConstantTopic, symbol.Locations.FirstOrDefault(), symbol.Name, interfaceName));
                continue;
            }

            // Checked on the value, not the literal: an empty topic's literal is `""`, which isn't blank text.
            if (topic.Length == 0)
            {
                context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.EmptyTopic, symbol.Locations.FirstOrDefault(), symbol.Name, interfaceName));
                continue;
            }

            var topicLiteral = SymbolDisplay.FormatLiteral(topic, quote: true);
            sb.Append("        services.TryAddKeyedScoped<").Append(interfaceName).Append(", ").Append(name).Append(">(typeof(").Append(name).AppendLine("));");
            sb.Append("        services.AddSingleton(new InboundProcessorTopic<").Append(interfaceName).Append(">(").Append(topicLiteral).Append(", typeof(").Append(name).AppendLine(")));");
        }
        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    // Unlike the shared IsCandidate, records count too: `sealed record X : INatsHandler` must not be skipped silently.
    private static bool IsHandlerCandidate(SyntaxNode node) =>
        node is ClassDeclarationSyntax { BaseList: not null } or RecordDeclarationSyntax { BaseList: not null };

    /// <summary>
    /// Every concrete class (or record class) implementing <paramref name="interfaceName"/>, unlike <see cref="BaseHttpRegistrationGenerator.GetSemanticTarget"/>:
    /// unsuitable handlers are reported (<see cref="DiagnosticDescriptors.NotRegistrableHandler"/>) instead of being silently skipped.
    /// Abstract classes are bases, not handlers, so they're ignored; record structs aren't classes.
    /// </summary>
    private static INamedTypeSymbol? GetInboundHandlerTarget(GeneratorSyntaxContext context, string interfaceName, CancellationToken cancellationToken)
    {
        var typeDecl = (TypeDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(typeDecl, cancellationToken) is not INamedTypeSymbol symbol)
            return null;

        if (symbol.TypeKind is not TypeKind.Class || symbol.IsAbstract || symbol.IsStatic)
            return null;

        return symbol.AllInterfaces.Any(a => string.Equals(a.Name, interfaceName, StringComparison.Ordinal)) ? symbol : null;
    }

    /// <summary>
    /// Generated registration code must reference the handler, and handlers are sealed by convention.
    /// </summary>
    private static bool IsRegistrableHandler(INamedTypeSymbol symbol)
    {
        if (!symbol.IsSealed)
            return false;

        for (var type = symbol; type is not null; type = type.ContainingType)
        {
            if (type.DeclaredAccessibility is not (Accessibility.Internal or Accessibility.Public))
                return false;
        }

        return true;
    }

    // Generated code registers a concrete type, so an open generic (`Handler<T>`) or one nested in a generic type
    // (`Outer<T>.Handler`) would emit an unknown type parameter and break the build in the generated file.
    private static bool IsGenericHandler(INamedTypeSymbol symbol)
    {
        for (var type = symbol; type is not null; type = type.ContainingType)
        {
            if (type.TypeParameters.Length > 0)
                return true;
        }

        return false;
    }

    /// <summary>
    /// Handlers ordered by name with their constant <c>Topic</c> value, trimmed like the runtime registry used to do
    /// (null when <c>Topic</c> isn't a compile-time constant). The emitted literal is escaped from this value at generation.
    /// </summary>
    private static IEnumerable<(string Name, string? Topic, INamedTypeSymbol Symbol)> GetInboundHandlers(SourceProductionContext context, Compilation compilation, ImmutableArray<INamedTypeSymbol?> classSymbols) =>
        classSymbols
            .Where(x => x is not null)
            .Distinct<INamedTypeSymbol?>(SymbolEqualityComparer.Default)
            .Select(x => (
                Name: x!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                Topic: GetConstantTopic(compilation, x, context.CancellationToken)?.Trim(),
                Symbol: x))
            .OrderBy(x => x.Name, StringComparer.Ordinal);

    // Supports `Topic => "x"`, `Topic { get => "x"; }`, `Topic { get { return "x"; } }` and `Topic { get; } = "x"`,
    // including const fields and string concatenation of constants; the nearest declaration in the class hierarchy wins.
    private static string? GetConstantTopic(Compilation compilation, INamedTypeSymbol symbol, CancellationToken cancellationToken)
    {
        for (var type = symbol; type is not null; type = type.BaseType)
        {
            var property = type.GetMembers(TopicPropertyName).OfType<IPropertySymbol>().FirstOrDefault();
            if (property is null)
                continue;

            var syntax = property.DeclaringSyntaxReferences
                .Select(r => r.GetSyntax(cancellationToken))
                .OfType<PropertyDeclarationSyntax>()
                .FirstOrDefault();
            if (syntax is null)
                return null;

            var expression = GetTopicExpression(syntax);
            if (expression is null)
                return null;

            var value = compilation.GetSemanticModel(expression.SyntaxTree).GetConstantValue(expression, cancellationToken);
            return value.HasValue ? value.Value as string : null;
        }

        return null;
    }

    private static ExpressionSyntax? GetTopicExpression(PropertyDeclarationSyntax syntax)
    {
        if (syntax.ExpressionBody is not null)
            return syntax.ExpressionBody.Expression;

        if (syntax.Initializer is not null)
            return syntax.Initializer.Value;

        var getter = syntax.AccessorList?.Accessors.FirstOrDefault(a => a.IsKind(SyntaxKind.GetAccessorDeclaration));
        if (getter?.ExpressionBody is not null)
            return getter.ExpressionBody.Expression;

        var statements = getter?.Body?.Statements;
        return statements is { Count: 1 } && statements.Value[0] is ReturnStatementSyntax { Expression: { } returned }
            ? returned
            : null;
    }
}
