using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators.Presentation;

[Generator]
public sealed class HttpEndpointsRegistrationGenerator : BaseRegistrationGenerator, IIncrementalGenerator
{
    private const string InterfaceName = "IHttpEndpoint";
    private const string NamespaceName = "Aspu.Common.Presentation.Abstractions.HttpAdapter";
    private const string InterfaceMetadata = $"{NamespaceName}.{InterfaceName}";

    private static readonly string Namespace = typeof(HttpEndpointsRegistrationGenerator).Namespace;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ///if (!Debugger.IsAttached)
        ///    Debugger.Launch();

        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidate(s), // quick filter
                transform: static (ctx, ct) => GetSemanticTarget(ctx, InterfaceName, ct)) // get symbol
            .Where(static m => m is not null)!;

        var collectedClasses = classDeclarations.Collect();
        var compilationProvider = context.CompilationProvider;
        var combined = compilationProvider.Combine(collectedClasses);

        context.RegisterSourceOutput(combined, static (spc, classSymbols) => Generate(spc, classSymbols!));
    }

    private static void Generate(SourceProductionContext context, (Compilation compilation, ImmutableArray<INamedTypeSymbol?> classes) data)
    {
        var (compilation, classSymbols) = data;

        if (classSymbols.IsDefaultOrEmpty)
            return;

        var str = GenerateString(compilation, classSymbols);
        context.AddSource("HttpEndpointsRegistration.g.cs", SourceText.From(str, Encoding.UTF8));
    }

#pragma warning disable MA0051 // Method is too long
    private static string GenerateString(Compilation compilation, ImmutableArray<INamedTypeSymbol?> classSymbols)
#pragma warning restore MA0051 // Method is too long
    {
        var items = GetSymbolNames(classSymbols);
        var interfaceNamespace = GetNamespace(compilation, NamespaceName, InterfaceName, InterfaceMetadata);
        var assemblyName = compilation.AssemblyName!.Replace(".Presentation", string.Empty);

        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine();
        sb.Append(Using).Append(interfaceNamespace).Append(';').AppendLine();
        sb.Append(Using).AppendLine("System.Globalization;");
        sb.Append(Using).AppendLine("Microsoft.AspNetCore.Builder;");
        sb.Append(Using).AppendLine("Microsoft.AspNetCore.Http;");
        sb.Append(Using).AppendLine("Microsoft.AspNetCore.Routing;");
        sb.AppendLine();
        sb.Append("namespace ").Append(assemblyName).Append('.').Append(Namespace).Append(';').AppendLine();
        sb.AppendLine();
        sb.AppendLine("internal static class HttpEndpointsRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static IEndpointRouteBuilder MapHttpEndpoints(");
        sb.AppendLine("        IEndpointRouteBuilder app,");
        sb.AppendLine("        RouteGroupBuilder routeGroupBuilder = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        var builder = routeGroupBuilder ?? app;");
        sb.AppendLine();
        foreach (var item in items.OrderBy(x => x, StringComparer.Ordinal))
            sb.Append("        MapEndpoints(new ").Append(item).AppendLine("(), builder);");
        sb.AppendLine();
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static IEndpointRouteBuilder MapEndpoints(");
        sb.Append("        ").Append(InterfaceName).AppendLine(" module,");
        sb.AppendLine("        IEndpointRouteBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        var group = string.IsNullOrWhiteSpace(module.Tags)");
        sb.AppendLine("            ? builder");
        sb.AppendLine("            : builder");
        sb.AppendLine("                .MapGroup(GetGroup(module.Tags))");
        sb.AppendLine("                .WithTags(GetTags(module.Tags));");
        sb.AppendLine("        module.MapEndpoint(group);");
        sb.AppendLine("        return group;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static string GetTags(string input) =>");
        sb.AppendLine("        string.IsNullOrWhiteSpace(input)");
        sb.AppendLine("            ? input");
        sb.AppendLine("            : string.Create(input.Length, input, (span, src) =>");
        sb.AppendLine("            {");
        sb.AppendLine("                span[0] = char.ToUpperInvariant(src[0]);");
        sb.AppendLine("                for (var i = 1; i < src.Length; i++)");
        sb.AppendLine("                    span[i] = char.ToLowerInvariant(src[i]);");
        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine("    private static string GetGroup(string input) =>");
        sb.AppendLine("        string.IsNullOrWhiteSpace(input)");
        sb.AppendLine("            ? input");
        sb.AppendLine("            : $\"/{input.ToLower(CultureInfo.InvariantCulture)}\";");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
