using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators.Presentation;

[Generator]
public sealed class MqttHandlersRegistrationGenerator : BaseHandlersRegistrationGenerator, IIncrementalGenerator
{
    private const string InterfaceName = "IMqttHandler";
    private const string NamespaceName = "Aspu.Common.Presentation.Abstractions.MqttAdapter";
    private const string InterfaceMetadata = $"{NamespaceName}.{InterfaceName}";

    private static readonly string Namespace = typeof(MqttHandlersRegistrationGenerator).Namespace;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ///if (!Debugger.IsAttached)
        ///    Debugger.Launch();

        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidate(s), // quick filter
                transform: static (ctx, ct) => GetInboundHandlerTarget(ctx, InterfaceName, ct)) // get symbol
            .Where(static m => m is not null)!;

        var collectedClasses = classDeclarations.Collect();
        var compilationProvider = context.CompilationProvider;
        var combined = compilationProvider.Combine(collectedClasses);

        context.RegisterSourceOutput(combined, static (spc, classSymbols) => Generate(spc, classSymbols!));
    }

    private static void Generate(SourceProductionContext context, (Compilation compilation, ImmutableArray<INamedTypeSymbol?> classes) data)
    {
        var (compilation, classSymbols) = data;

        if (classSymbols.IsDefaultOrEmpty)
            return;

        var str = GenerateString(context, compilation, classSymbols);
        context.AddSource("MqttHandlersRegistration.g.cs", SourceText.From(str, Encoding.UTF8));
    }

    private static string GenerateString(SourceProductionContext context, Compilation compilation, ImmutableArray<INamedTypeSymbol?> classSymbols)
    {
        var interfaceNamespace = GetNamespace(compilation, NamespaceName, InterfaceName, InterfaceMetadata);
        var assemblyName = compilation.AssemblyName!.Replace(".Presentation", string.Empty);

        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine();
        sb.Append(Using).Append(interfaceNamespace).Append(';').AppendLine();
        sb.Append(Using).AppendLine("Microsoft.Extensions.DependencyInjection;");
        sb.Append(Using).AppendLine("Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.Append(Using).Append(InboundProcessorNamespace).Append(';').AppendLine();
        sb.AppendLine();
        sb.Append("namespace ").Append(assemblyName).Append('.').Append(Namespace).Append(';').AppendLine();
        sb.AppendLine();
        sb.AppendLine("internal static class MqttHandlersRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddMqttHandlers(");
        sb.AppendLine("        this IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var (name, topicLiteral, symbol) in GetInboundHandlers(context, compilation, classSymbols))
        {
            if (!IsRegistrableHandler(symbol))
            {
                context.ReportDiagnostic(Diagnostic.Create(NotRegistrableHandler, symbol.Locations.FirstOrDefault(), symbol.Name, InterfaceName));
                continue;
            }

            if (topicLiteral is null)
            {
                context.ReportDiagnostic(Diagnostic.Create(NonConstantTopic, symbol.Locations.FirstOrDefault(), symbol.Name, InterfaceName));
                continue;
            }

            sb.Append("        services.TryAddKeyedScoped<").Append(InterfaceName).Append(", ").Append(name).Append(">(typeof(").Append(name).AppendLine("));");
            sb.Append("        services.AddSingleton(new InboundProcessorTopic<").Append(InterfaceName).Append(">(").Append(topicLiteral).Append(", typeof(").Append(name).AppendLine(")));");
        }
        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
