using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators.Presentation;

[Generator]
public sealed class MqttHandlersRegistrationGenerator : BaseRegistrationGenerator, IIncrementalGenerator
{
    private const string InterfaceName = "IMqttHandler";
    private const string NamespaceName = "Aspu.Common.Presentation.Abstractions.MqttAdapter";
    private const string InterfaceMetadata = $"{NamespaceName}.{InterfaceName}";

    private static readonly string Namespace = typeof(MqttHandlersRegistrationGenerator).Namespace;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ///if (!Debugger.IsAttached)
        ///    Debugger.Launch();

        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidate(s), // quick filter
                transform: static (ctx, ct) => GetSemanticTarget(ctx, InterfaceName, ct)) // get symbol
            .Where(static m => m is not null)!;

        var collectedClasses = classDeclarations.Collect();
        var compilationProvider = context.CompilationProvider;
        var combined = compilationProvider.Combine(collectedClasses);

        context.RegisterSourceOutput(combined, static (spc, classSymbols) => Generate(spc, classSymbols!));
    }

    private static void Generate(SourceProductionContext context, (Compilation compilation, ImmutableArray<INamedTypeSymbol?> classes) data)
    {
        var (compilation, classSymbols) = data;

        if (classSymbols.IsDefaultOrEmpty)
            return;

        var str = GenerateString(compilation, classSymbols);
        context.AddSource("MqttHandlersRegistration.g.cs", SourceText.From(str, Encoding.UTF8));
    }

    private static string GenerateString(Compilation compilation, ImmutableArray<INamedTypeSymbol?> classSymbols)
    {
        var items = GetSymbolNames(classSymbols);
        var interfaceNamespace = GetNamespace(compilation, NamespaceName, InterfaceName, InterfaceMetadata);
        var assemblyName = compilation.AssemblyName!.Replace(".Presentation", string.Empty);

        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine();
        sb.Append(Using).Append(interfaceNamespace).Append(';').AppendLine();
        sb.Append(Using).AppendLine("Microsoft.Extensions.DependencyInjection;");
        sb.Append(Using).AppendLine("Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.Append("namespace ").Append(assemblyName).Append('.').Append(Namespace).Append(';').AppendLine();
        sb.AppendLine();
        sb.AppendLine("internal static class MqttHandlersRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddMqttHandlers(");
        sb.AppendLine("        this IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var item in items.OrderBy(x => x, StringComparer.Ordinal))
            sb.Append("        services.TryAddEnumerable(ServiceDescriptor.Scoped<").Append(InterfaceName).Append(", ").Append(item).AppendLine(">());");
        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
