using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators.Application;

[Generator]
public sealed class SignalrNotificationRegistrationGenerator : BaseRegistrationGenerator, IIncrementalGenerator
{
    private const string InterfaceName = "ISignalrNotification";
    private const string NamespaceName = "Aspu.Common.Application.Ports.SignalrPort";
    private const string InterfaceMetadata = $"{NamespaceName}.{InterfaceName}";

    private static readonly string Namespace = typeof(SignalrNotificationRegistrationGenerator).Namespace;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ///if (!Debugger.IsAttached)
        ///    Debugger.Launch();

        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidate(s), // quick filter
                transform: static (ctx, ct) => GetSemanticTarget(ctx, InterfaceName, ct)) // get symbol
            .Where(static m => m is not null)!;

        var collectedClasses = classDeclarations.Collect();
        var compilationProvider = context.CompilationProvider;
        var combined = compilationProvider.Combine(collectedClasses);

        context.RegisterSourceOutput(combined, static (spc, classSymbols) => Generate(spc, classSymbols!));
    }

    private static void Generate(SourceProductionContext context, (Compilation compilation, ImmutableArray<INamedTypeSymbol?> classes) data)
    {
        var (compilation, classSymbols) = data;

        if (classSymbols.IsDefaultOrEmpty)
            return;

        var str = GenerateString(compilation, classSymbols);
        context.AddSource("SignalrNotificationRegistration.g.cs", SourceText.From(str, Encoding.UTF8));
    }

#pragma warning disable MA0051 // Method is too long
    private static string GenerateString(Compilation compilation, ImmutableArray<INamedTypeSymbol?> classSymbols)
#pragma warning restore MA0051 // Method is too long
    {
        var items = GetSymbolNames(classSymbols);
        var interfaceNamespace = GetNamespace(compilation, NamespaceName, InterfaceName, InterfaceMetadata);
        var assemblyName = compilation.AssemblyName!.Replace(".Application", string.Empty);

        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine();
        sb.Append(Using).Append(interfaceNamespace).Append(';').AppendLine();
        sb.Append(Using).AppendLine("System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.Append("namespace ").Append(assemblyName).Append('.').Append(Namespace).Append(';').AppendLine();
        sb.AppendLine();
        sb.AppendLine("public interface ISignalrNotificationPublisher");
        sb.AppendLine("{");
        sb.AppendLine("    Task PublishAsync(ISignalrNotification notification, CancellationToken cancellationToken = default);");
        sb.AppendLine();
        foreach (var item in items.OrderBy(x => x, StringComparer.Ordinal))
            sb.Append("    Task PublishAsync(").Append(item).AppendLine(" notification, CancellationToken cancellationToken = default);").AppendLine();
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public interface ISignalrNotificationsHub");
        sb.AppendLine("{");

        foreach (var item in classSymbols.Where(x => !string.IsNullOrWhiteSpace(x?.Name)))
            sb.Append("    Task ").Append(item!.Name).Append('(').Append(item!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).AppendLine(" notification);").AppendLine();
        sb.AppendLine("}");
        return sb.ToString();
    }
}
