using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators.Application;

[Generator]
public sealed class SignalrNotificationRegistrationGenerator : BaseRegistrationGenerator, IIncrementalGenerator
{
    private const string InterfaceName = "ISignalrNotification";
    private const string NamespaceName = "Aspu.Common.Application.Ports.SignalrPort";
    private const string InterfaceMetadata = $"{NamespaceName}.{InterfaceName}";
    private static readonly string Namespace = typeof(SignalrNotificationRegistrationGenerator).Namespace;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ///if (!Debugger.IsAttached)
        ///    Debugger.Launch();

        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidate(s), // quick filter
                transform: static (ctx, ct) => GetSemanticTarget(ctx, InterfaceName, ct)) // get symbol
            .Where(static m => m is not null)!;

        var collectedClasses = classDeclarations.Collect();
        var compilationProvider = context.CompilationProvider;
        var combined = compilationProvider.Combine(collectedClasses);

        context.RegisterSourceOutput(combined, static (spc, classSymbols) => Generate(spc, classSymbols!));
    }

    private static void Generate(SourceProductionContext context, (Compilation compilation, ImmutableArray<INamedTypeSymbol?> classes) data)
    {
        var (compilation, classSymbols) = data;

        if (classSymbols.IsDefaultOrEmpty)
            return;

        var orderedClasses = classSymbols
            .Where(static x => x is not null)
            .Select(static x => x!)
            .OrderBy(static x => x.Name, StringComparer.Ordinal)
            .ToImmutableArray();

        var interfaceNamespace = GetNamespace(compilation, NamespaceName, InterfaceName, InterfaceMetadata);
        var assemblyName = compilation.AssemblyName!.Replace(".Application", string.Empty);
        var generatorNamespace = $"{assemblyName}.{Namespace}";

        context.AddSource(
            "SignalrNotificationRegistration.g.cs",
            SourceText.From(GenerateInterfaces(orderedClasses, interfaceNamespace, generatorNamespace), Encoding.UTF8));

        context.AddSource(
            "SignalrNotificationPublisher.g.cs",
            SourceText.From(GeneratePublisher(orderedClasses, interfaceNamespace, generatorNamespace), Encoding.UTF8));
    }

    private static string GenerateInterfaces(
        ImmutableArray<INamedTypeSymbol> classSymbols,
        string interfaceNamespace,
        string generatorNamespace)
    {
        var items = GetSymbolNames(classSymbols.Cast<INamedTypeSymbol?>().ToImmutableArray());

        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine();
        sb.Append(Using).Append(interfaceNamespace).Append(';').AppendLine();
        sb.Append(Using).AppendLine("System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.Append("namespace ").Append(generatorNamespace).Append(';').AppendLine();
        sb.AppendLine();
        sb.AppendLine("public interface ISignalrNotificationPublisher");
        sb.AppendLine("{");
        sb.AppendLine("    Task PublishAsync(ISignalrNotification notification, CancellationToken cancellationToken = default);");
        sb.AppendLine();
        foreach (var item in items.OrderBy(x => x, StringComparer.Ordinal))
            sb.Append("    Task PublishAsync(").Append(item).AppendLine(" notification, CancellationToken cancellationToken = default);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public interface ISignalrNotificationsHub");
        sb.AppendLine("{");

        foreach (var item in classSymbols)
            sb.Append("    Task ").Append(item.Name).Append('(').Append(item.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).AppendLine(" notification);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GeneratePublisher(
        ImmutableArray<INamedTypeSymbol> classSymbols,
        string interfaceNamespace,
        string generatorNamespace)
    {
        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine();
        sb.Append(Using).Append(interfaceNamespace).Append(';').AppendLine();
        sb.AppendLine();
        sb.Append("namespace ").Append(generatorNamespace).Append(';').AppendLine();
        sb.AppendLine();
        sb.AppendLine("public static class SignalrNotificationPublisherRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static ISignalrNotificationPublisher Create(Func<ISignalrNotificationsHub> getClients) =>");
        sb.AppendLine("        new SignalrNotificationPublisherImpl(getClients);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("internal sealed class SignalrNotificationPublisherImpl(Func<ISignalrNotificationsHub> getClients) : ISignalrNotificationPublisher");
        sb.AppendLine("{");

        foreach (var item in classSymbols)
        {
            var typeName = item.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.Append("    public Task PublishAsync(").Append(typeName).AppendLine(" notification, CancellationToken cancellationToken = default) =>");
            sb.Append("        getClients().").Append(item.Name).AppendLine("(notification);");
            sb.AppendLine();
        }

        sb.AppendLine("    public Task PublishAsync(ISignalrNotification notification, CancellationToken cancellationToken = default) =>");
        sb.AppendLine("        notification switch");
        sb.AppendLine("        {");

        foreach (var item in classSymbols)
        {
            var typeName = item.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var parameterName = ToCamelCase(item.Name);
            sb.Append("            ").Append(typeName).Append(' ').Append(parameterName).Append(" => PublishAsync(").Append(parameterName).AppendLine(", cancellationToken),");
        }

        sb.AppendLine("            _ => throw new NotSupportedException($\"SignalR notification type '{notification.GetType().Name}' is not registered.\"),");
        sb.AppendLine("        };");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ToCamelCase(string value)
    {
        if (value.Length == 0)
            return value;

        if (value.Length == 1)
            return value.ToLowerInvariant();

        return char.ToLowerInvariant(value[0]) + value.Substring(1);
    }
}
