using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators.Application;

[Generator]
public sealed class SignalrNotificationRegistrationGenerator : BaseRegistrationGenerator, IIncrementalGenerator
{
    private const string InterfaceName = "ISignalrNotification";
    private const string NamespaceName = "Aspu.Common.Application.Ports.SignalrPort";
    private const string InterfaceMetadata = $"{NamespaceName}.{InterfaceName}";

    private static readonly string Namespace = typeof(SignalrNotificationRegistrationGenerator).Namespace;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ///if (!Debugger.IsAttached)
        ///    Debugger.Launch();

        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidate(s), // quick filter
                transform: static (ctx, ct) => GetSemanticTarget(ctx, InterfaceName, ct)) // get symbol
            .Where(static m => m is not null)!;

        var collectedClasses = classDeclarations.Collect();
        var compilationProvider = context.CompilationProvider;
        var combined = compilationProvider.Combine(collectedClasses);

        context.RegisterSourceOutput(combined, static (spc, classSymbols) => Generate(spc, classSymbols!));
    }

    private static void Generate(SourceProductionContext context, (Compilation compilation, ImmutableArray<INamedTypeSymbol?> classes) data)
    {
        var (compilation, classSymbols) = data;

        if (classSymbols.IsDefaultOrEmpty)
            return;

        var str = GenerateString(compilation, classSymbols);
        context.AddSource("SignalrNotificationRegistration.g.cs", SourceText.From(str, Encoding.UTF8));
    }

#pragma warning disable MA0051 // Method is too long
    private static string GenerateString(Compilation compilation, ImmutableArray<INamedTypeSymbol?> classSymbols)
#pragma warning restore MA0051 // Method is too long
    {
        var items = classSymbols
            .Where(x => !string.IsNullOrWhiteSpace(x?.Name))
            .OrderBy(x => x!.Name, StringComparer.Ordinal)
            .ToDictionary(x => x!.Name, x => x!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal);

        var interfaceNamespace = GetNamespace(compilation, NamespaceName, InterfaceName, InterfaceMetadata);
        var assemblyName = compilation.AssemblyName!.Replace(".Application", string.Empty);

        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append(Using).Append(interfaceNamespace).Append(';').AppendLine();
        sb.Append(Using).AppendLine("System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.Append("namespace ").Append(assemblyName).Append('.').Append(Namespace).Append(';').AppendLine();
        sb.AppendLine();

        sb.AppendLine("public interface ISignalrNotificationsHub");
        sb.AppendLine("{");
        foreach (var item in items)
            sb.Append("    Task ").Append(item!.Key).Append('(').Append(item.Value).AppendLine(" notification);").AppendLine();
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("public interface ISignalrNotificationPublisher");
        sb.AppendLine("{");
        sb.AppendLine("    Task PublishAsync(ISignalrNotification notification, CancellationToken cancellationToken = default);");
        sb.AppendLine();
        foreach (var item in items.Values)
            sb.Append("    Task PublishAsync(").Append(item).AppendLine(" notification, CancellationToken cancellationToken = default);").AppendLine();
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("public static class SignalrNotificationPublisherRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static ISignalrNotificationPublisher Create(");
        sb.AppendLine("        Func<string?, string?> getHost,");
        sb.AppendLine("        Func<ISignalrNotificationsHub> getClients,");
        sb.AppendLine("        Func<string?, ISignalrNotificationsHub> getClient) =>");
        sb.AppendLine("        new SignalrNotificationPublisherImpl(getHost, getClients, getClient);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("internal sealed class SignalrNotificationPublisherImpl(");
        sb.AppendLine("    Func<string?, string?> getHost,");
        sb.AppendLine("    Func<ISignalrNotificationsHub> getClients,");
        sb.AppendLine("    Func<string?, ISignalrNotificationsHub> getClient)");
        sb.AppendLine("    : ISignalrNotificationPublisher");
        sb.AppendLine("{");

        foreach (var item in items)
        {
            sb.Append("    public Task PublishAsync(").Append(item!.Value).AppendLine(" notification, CancellationToken cancellationToken = default)");
            sb.AppendLine("    {");
            sb.AppendLine("        var connectionId = getHost(notification.Host);");
            sb.AppendLine("        return string.IsNullOrWhiteSpace(connectionId)");
            sb.Append("            ? getClients().").Append(item.Key).AppendLine("(notification)");
            sb.Append("            : getClient(connectionId).").Append(item.Key).AppendLine("(notification);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("    public Task PublishAsync(ISignalrNotification notification, CancellationToken cancellationToken = default) =>");
        sb.AppendLine("        notification switch");
        sb.AppendLine("        {");

        foreach (var item in items)
        {
            var parameterName = item!.Key.ToLowerInvariant();
            sb.Append("            ").Append(item!.Value).Append(' ').Append(parameterName).Append(" => PublishAsync(").Append(parameterName).AppendLine(", cancellationToken),");
        }

        sb.AppendLine("            _ => throw new NotSupportedException($\"SignalR notification type '{notification.GetType().Name}' is not registered.\"),");
        sb.AppendLine("        };");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
