using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators.Application;

[Generator]
public sealed class ValidatorRegistrationGenerator : BaseRegistrationGenerator, IIncrementalGenerator
{
    private const string InterfaceName = "IValidator";
    private const string BaseClassName = "FluentValidation.AbstractValidator`1";

    private static string Namespace => typeof(ValidatorRegistrationGenerator).Namespace;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ///if (!Debugger.IsAttached)
        ///    Debugger.Launch();

        var classDeclarations = context.SyntaxProvider
         .CreateSyntaxProvider(
             predicate: static (s, _) => IsCandidate(s), // quick filter
             transform: static (ctx, ct) => GetSemanticTarget(ctx, InterfaceName, ct)) // get symbol
         .Where(static m => m is not null)!;

        var collectedClasses = classDeclarations.Collect();
        var compilationProvider = context.CompilationProvider;
        var combined = compilationProvider.Combine(collectedClasses);

        context.RegisterSourceOutput(combined, static (spc, classSymbols) => Generate(spc, classSymbols!));
    }

    private static void Generate(SourceProductionContext context, (Compilation compilation, ImmutableArray<INamedTypeSymbol?> classes) data)
    {
        var (compilation, classSymbols) = data;

        if (classSymbols.IsDefaultOrEmpty)
            return;

        var assemblyName = compilation.AssemblyName!.Replace(".Application", string.Empty);
        var abstractValidatorSymbol = compilation.GetTypeByMetadataName(BaseClassName);

        var sb = new StringBuilder(4096)
            .AppendLine("// <auto-generated>")
            .AppendLine();

        var namespaces = classSymbols
            .Where(x => x is not null)
            .Select(x => x!.ContainingNamespace)
            .Where(x => !x.IsGlobalNamespace)
            .Select(x => x.ToDisplayString())
            .OrderBy(x => x, StringComparer.Ordinal)
            .ToImmutableHashSet();
        foreach (var @namespace in namespaces)
            sb.Append("using ").Append(@namespace).Append(';').AppendLine();

        sb.Append("using ").Append("FluentValidation").Append(';').AppendLine();
        sb.Append("using ").Append("Microsoft.Extensions.DependencyInjection").Append(';').AppendLine();
        sb.AppendLine();
        sb.Append("namespace ").Append(assemblyName).Append('.').Append(Namespace).Append(';').AppendLine();
        sb.AppendLine();
        sb.AppendLine("public static class ValidatorRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddValidators(this IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var classSymbol in classSymbols
            .Where(x => x is not null)
            .OrderBy(x => x!.Name, StringComparer.Ordinal))
        {
            var baseClassSymbol = FindBaseClass(classSymbol, abstractValidatorSymbol);
            var modelTypeName = baseClassSymbol?.TypeArguments[0]?.ToDisplayString();
            if (string.IsNullOrWhiteSpace(modelTypeName))
                continue;

            sb.Append("        services.AddScoped<").Append(InterfaceName).Append('<').Append(modelTypeName).Append(">, ").Append(classSymbol!.Name).AppendLine(">();");
        }
        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        context.AddSource("ValidatorRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static INamedTypeSymbol? FindBaseClass(INamedTypeSymbol? symbol, INamedTypeSymbol? baseClassSymbol)
    {
        var baseType = symbol?.BaseType;
        return baseType is null ||
            baseClassSymbol is null ||
            !SymbolEqualityComparer.Default.Equals(baseType.OriginalDefinition, baseClassSymbol)
                ? null
                : baseType;
    }
}
