using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SourceGeneratorsLibrary;

[Generator]
public sealed class DomainEnumGenerator : GeneratorInternal<DomainEnumGenerator>, IIncrementalGenerator
{
    private const string SummaryStart = "    /// <summary>";
    private const string SummaryEnd = "    /// </summary>";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ///#if DEBUG
        ///if (!Debugger.IsAttached)
        ///    Debugger.Launch();
        ///#endif

        // Create attribute
        CreateAttribute(context);

        // Find all class declarations with attribute
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidate(s), // quick filter
                transform: static (ctx, _) => GetSemanticTarget(ctx)) // get symbol
            .Where(static m => m is not null)!;

        // Generate code for each matched class
        context.RegisterSourceOutput(classDeclarations, static (spc, classSymbol) =>
            GenerateSerializer(spc, classSymbol!));
    }

#pragma warning disable MA0051 // Method is too long
    private static void GenerateSerializer(SourceProductionContext context, INamedTypeSymbol classSymbol)
#pragma warning restore MA0051 // Method is too long
    {
        var @namespace = classSymbol.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : classSymbol.ContainingNamespace.ToDisplayString();
        var className = classSymbol.Name;

        var props = classSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public)
            .Where(p => p.IsStatic)
            .Where(p => p.GetMethod is not null)
            .Where(p => p.SetMethod is null)
            .ToList();

        var sb = new StringBuilder()
            .AppendLine("// <auto-generated>")
            .AppendLine()
            .AppendLine("using Aspu.Common.Domain;")
            .AppendLine("using Aspu.Common.Domain.Errors;")
            .AppendLine("using Aspu.Common.Domain.Results;")
            .AppendLine("using CSharpFunctionalExtensions;")
            .AppendLine("using System.Diagnostics.CodeAnalysis;")
            .AppendLine();

        if (!string.IsNullOrEmpty(@namespace))
        {
            sb.Append("namespace ")
              .Append(@namespace)
              .AppendLine(";")
              .AppendLine();
        }

        sb.Append("public partial class ")
          .Append(className)
          .AppendLine(" : ValueObject")
          .AppendLine("{")
          .AppendLine(SummaryStart)
          .AppendLine("    ///     Ctr")
          .AppendLine(SummaryEnd)
          .AppendLine("    [ExcludeFromCodeCoverage]")
          .Append("    private ").Append(className).AppendLine("() { }")
          .AppendLine()
          .AppendLine(SummaryStart)
          .AppendLine("    ///     Ctr")
          .AppendLine(SummaryEnd)
          .AppendLine("    /// <param name=\"name\">Name</param>")
          .Append("    public ").Append(className).AppendLine("(string name) : this()")
          .AppendLine("    {")
          .AppendLine("        Name = name.ToLowerInvariant();")
          .AppendLine("    }")
          .AppendLine()
          .AppendLine(SummaryStart)
          .AppendLine("    ///     Name")
          .AppendLine(SummaryEnd)
          .AppendLine("    public string Name { get; init; }")
          .AppendLine()
          .AppendLine(SummaryStart)
          .AppendLine("    ///     List of values")
          .AppendLine(SummaryEnd)
          .AppendLine("    /// <returns></returns>")
          .Append("    public static IEnumerable<").Append(className).AppendLine("> GetList() =>")
          .Append("        [");

        if (props.Count > 0)
        {
            sb.Append(' ');
            for (var i = 0; i < props.Count - 1; i++)
            {
                sb.Append(props[i].Name)
                  .Append(", ");
            }
            sb.Append(props[props.Count - 1].Name);
        }

        sb.AppendLine(" ];")
          .AppendLine()
          .AppendLine(SummaryStart)
          .AppendLine("    ///     Gets value by name")
          .AppendLine(SummaryEnd)
          .AppendLine("    /// <param name=\"name\"></param>")
          .AppendLine("    /// <returns></returns>")
          .Append("    public static Aspu.Common.Domain.Results.Result<").Append(className).AppendLine(", Error> GetByName(string name)")
          .AppendLine("    {")
          .AppendLine("        var value = GetList().FirstOrDefault(s => string.Equals(s.Name, name, StringComparison.OrdinalIgnoreCase));")
          .AppendLine("        return value is not null ? value : Error.ValueIsInvalid(name);")
          .AppendLine("    }")
          .AppendLine()
          .AppendLine("    [ExcludeFromCodeCoverage]")
          .AppendLine("    public override string ToString() =>")
          .AppendLine("        Name;")
          .AppendLine()
          .AppendLine("    [ExcludeFromCodeCoverage]")
          .AppendLine("    protected override IEnumerable<object> GetEqualityComponents()")
          .AppendLine("    {")
          .AppendLine("        yield return Name;")
          .AppendLine("    }")
          .AppendLine("}");

        context.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}

