using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SourceGeneratorsLibrary;

[Generator]
public sealed class EndpointsRegistrationGenerator : IIncrementalGenerator
{
    private const string InterfaceName = "IEndpoint";

    private static string Namespace => typeof(EndpointsRegistrationGenerator).Namespace;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ///if (!Debugger.IsAttached)
        ///    Debugger.Launch();

        var classDeclarations = context.SyntaxProvider
         .CreateSyntaxProvider(
             predicate: static (s, _) => IsCandidate(s), // quick filter
             transform: static (ctx, _) => GetSemanticTarget(ctx)) // get symbol
         .Where(static m => m is not null)!;

        var collectedClasses = classDeclarations.Collect();
        var compilationProvider = context.CompilationProvider;
        var combined = compilationProvider.Combine(collectedClasses);

        context.RegisterSourceOutput(combined, static (spc, classSymbols) => Generate(spc, classSymbols!));
    }

    private static bool IsCandidate(SyntaxNode node) =>
        node is ClassDeclarationSyntax cds && cds.BaseList is not null;

    private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
            return null;

        if (symbol.TypeKind is not TypeKind.Class)
            return null;

        if (symbol.DeclaredAccessibility is not Accessibility.Internal)
            return null;

        if (!symbol.IsSealed)
            return null;

        return symbol.AllInterfaces.Any(a =>
            string.Equals(a.Name, InterfaceName, StringComparison.OrdinalIgnoreCase))
                ? symbol : null;
    }

    private static void Generate(SourceProductionContext context, (Compilation compilation, ImmutableArray<INamedTypeSymbol?> classes) data)
    {
        var (compilation, classSymbols) = data;

        if (classSymbols.IsDefaultOrEmpty)
            return;

        var interfaceSymbol = FindInterface(compilation, InterfaceName);
        var interfaceNamespace = interfaceSymbol is null ||
            interfaceSymbol.ContainingNamespace.IsGlobalNamespace
                ? "Aspu.Common.Presentation.Endpoints"
                : interfaceSymbol.ContainingNamespace.ToDisplayString();

        var assemblyName = compilation.AssemblyName;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// {DateTime.Now:yyyy-MM-dd HH:mm:ss.ffff}");
        sb.AppendLine();

        var namespaces = classSymbols
            .Where(x => x is not null)
            .Select(x => x!.ContainingNamespace)
            .Where(x => !x.IsGlobalNamespace)
            .Select(x => x.ToDisplayString())
            .ToList();
        namespaces.AddRange([
            interfaceNamespace,
            "System.Globalization",
            "Microsoft.AspNetCore.Builder",
            "Microsoft.AspNetCore.Http",
            "Microsoft.AspNetCore.Routing"
        ]);
        foreach (var @namespace in namespaces
            .OrderBy(x => x)
            .Distinct())
            sb.AppendLine($"using {@namespace};");
        sb.AppendLine();

        sb.AppendLine($"namespace {assemblyName}.{Namespace};");
        sb.AppendLine();
        sb.AppendLine("public static class EndpointsRegistrationGenerator");
        sb.AppendLine("{");
        sb.AppendLine("    public static IEndpointRouteBuilder MapEndpoints(");
        sb.AppendLine("        IEndpointRouteBuilder app,");
        sb.AppendLine("        RouteGroupBuilder routeGroupBuilder = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        var builder = routeGroupBuilder ?? app;");
        sb.AppendLine();
        foreach (var classSymbol in classSymbols
            .Where(x => x is not null)
            .OrderBy(x => x!.Name))
            sb.AppendLine($"        MapEndpoints(new {classSymbol!.Name}(), builder);");
        sb.AppendLine();
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static IEndpointRouteBuilder MapEndpoints(");
        sb.AppendLine("        IEndpoint module,");
        sb.AppendLine("        IEndpointRouteBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        var group = string.IsNullOrWhiteSpace(module.Tags)");
        sb.AppendLine("            ? builder");
        sb.AppendLine("            : builder");
        sb.AppendLine("                .MapGroup(GetGroup(module.Tags))");
        sb.AppendLine("                .WithTags(GetTags(module.Tags));");
        sb.AppendLine("        module.MapEndpoint(group);");
        sb.AppendLine("        return group;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static string GetTags(string input) =>");
        sb.AppendLine("        string.IsNullOrWhiteSpace(input)");
        sb.AppendLine("            ? input");
        sb.AppendLine("            : string.Create(input.Length, input, (span, src) =>");
        sb.AppendLine("            {");
        sb.AppendLine("                span[0] = char.ToUpperInvariant(src[0]);");
        sb.AppendLine("                for (var i = 1; i < src.Length; i++)");
        sb.AppendLine("                    span[i] = char.ToLowerInvariant(src[i]);");
        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine("    private static string GetGroup(string input) =>");
        sb.AppendLine("        string.IsNullOrWhiteSpace(input)");
        sb.AppendLine("            ? input");
        sb.AppendLine("            : $\"/{input.ToLower(CultureInfo.InvariantCulture)}\";");
        sb.AppendLine("}");
        context.AddSource("EndpointsRegistrationGenerator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static INamedTypeSymbol? FindInterface(Compilation compilation, string name) =>
        FindInNamespace(compilation.GlobalNamespace, name);

    private static INamedTypeSymbol? FindInNamespace(INamespaceSymbol ns, string name)
    {
        foreach (var member in ns.GetMembers())
        {
            if (member is INamespaceSymbol childNs)
            {
                var found = FindInNamespace(childNs, name);
                if (found is not null)
                    return found;

                continue;
            }

            if (member is INamedTypeSymbol type && type.TypeKind == TypeKind.Interface && type.Name == name)
                return type;
        }
        return null;
    }

}
