using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SourceGeneratorsLibrary;

[Generator]
public sealed class EndpointsRegistrationGenerator : IIncrementalGenerator
{
    private const string InterfaceName = "IEndpoint";
    private const string IEndpointMetadataName = "Aspu.Common.Presentation.Endpoints.IEndpoint";

    private static string Namespace => typeof(EndpointsRegistrationGenerator).Namespace;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ///if (!Debugger.IsAttached)
        ///    Debugger.Launch();

        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidate(s), // quick filter
                transform: static (ctx, ct) => GetSemanticTarget(ctx, ct)) // get symbol
            .Where(static m => m is not null)!;

        var collectedClasses = classDeclarations.Collect();
        var compilationProvider = context.CompilationProvider;
        var combined = compilationProvider.Combine(collectedClasses);

        context.RegisterSourceOutput(combined, static (spc, classSymbols) => Generate(spc, classSymbols!));
    }

    private static bool IsCandidate(SyntaxNode node) =>
        node is ClassDeclarationSyntax cds && cds.BaseList is not null;

    private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classDecl, cancellationToken) is not INamedTypeSymbol symbol)
            return null;

        if (symbol.TypeKind is not TypeKind.Class)
            return null;

        if (symbol.DeclaredAccessibility is not Accessibility.Internal)
            return null;

        if (!symbol.IsSealed)
            return null;

        return symbol.AllInterfaces.Any(a =>
            string.Equals(a.Name, InterfaceName, StringComparison.Ordinal))
                ? symbol : null;
    }

#pragma warning disable MA0051 // Method is too long
    private static void Generate(SourceProductionContext context, (Compilation compilation, ImmutableArray<INamedTypeSymbol?> classes) data)
#pragma warning restore MA0051 // Method is too long
    {
        var (compilation, classSymbols) = data;

        if (classSymbols.IsDefaultOrEmpty)
            return;

        var assemblyName = compilation.AssemblyName;

        var sb = new StringBuilder()
            .AppendLine("// <auto-generated>")
            .AppendFormat(CultureInfo.InvariantCulture, "// {0:yyyy-MM-dd HH:mm:ss.ffff}", DateTime.Now)
            .AppendLine()
            .AppendLine();

        var namespaces = classSymbols
            .Where(x => x is not null)
            .Select(x => x!.ContainingNamespace)
            .Where(x => !x.IsGlobalNamespace)
            .Select(x => x.ToDisplayString())
            .OrderBy(x => x, StringComparer.OrdinalIgnoreCase)
            .ToImmutableHashSet();
        foreach (var @namespace in namespaces)
            sb.Append("using ").Append(@namespace).Append(';').AppendLine();

        var interfaceSymbol = compilation.GetTypeByMetadataName(IEndpointMetadataName) ?? FindInterface(compilation, InterfaceName);
        var interfaceNamespace = interfaceSymbol?.ContainingNamespace.IsGlobalNamespace != false
                ? "Aspu.Common.Presentation.Endpoints"
                : interfaceSymbol.ContainingNamespace.ToDisplayString();

        sb.Append("using ").Append(interfaceNamespace).Append(';').AppendLine();
        sb.Append("using ").Append("System.Globalization").Append(';').AppendLine();
        sb.Append("using ").Append("Microsoft.AspNetCore.Builder").Append(';').AppendLine();
        sb.Append("using ").Append("Microsoft.AspNetCore.Http").Append(';').AppendLine();
        sb.Append("using ").Append("Microsoft.AspNetCore.Routing").Append(';').AppendLine();
        sb.AppendLine();

        sb.Append("namespace ").Append(assemblyName).Append('.').Append(Namespace).Append(';').AppendLine();
        sb.AppendLine();
        sb.AppendLine("public static class EndpointsRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static IEndpointRouteBuilder MapEndpoints(");
        sb.AppendLine("        IEndpointRouteBuilder app,");
        sb.AppendLine("        RouteGroupBuilder routeGroupBuilder = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        var builder = routeGroupBuilder ?? app;");
        sb.AppendLine();
        foreach (var classSymbol in classSymbols.Where(x => x is not null).OrderBy(x => x!.Name, StringComparer.Ordinal))
            sb.Append("        MapEndpoints(new ").Append(classSymbol!.Name).AppendLine("(), builder);");
        sb.AppendLine();
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static IEndpointRouteBuilder MapEndpoints(");
        sb.AppendLine("        IEndpoint module,");
        sb.AppendLine("        IEndpointRouteBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        var group = string.IsNullOrWhiteSpace(module.Tags)");
        sb.AppendLine("            ? builder");
        sb.AppendLine("            : builder");
        sb.AppendLine("                .MapGroup(GetGroup(module.Tags))");
        sb.AppendLine("                .WithTags(GetTags(module.Tags));");
        sb.AppendLine("        module.MapEndpoint(group);");
        sb.AppendLine("        return group;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static string GetTags(string input) =>");
        sb.AppendLine("        string.IsNullOrWhiteSpace(input)");
        sb.AppendLine("            ? input");
        sb.AppendLine("            : string.Create(input.Length, input, (span, src) =>");
        sb.AppendLine("            {");
        sb.AppendLine("                span[0] = char.ToUpperInvariant(src[0]);");
        sb.AppendLine("                for (var i = 1; i < src.Length; i++)");
        sb.AppendLine("                    span[i] = char.ToLowerInvariant(src[i]);");
        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine("    private static string GetGroup(string input) =>");
        sb.AppendLine("        string.IsNullOrWhiteSpace(input)");
        sb.AppendLine("            ? input");
        sb.AppendLine("            : $\"/{input.ToLower(CultureInfo.InvariantCulture)}\";");
        sb.AppendLine("}");
        context.AddSource("EndpointsRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static INamedTypeSymbol? FindInterface(Compilation compilation, string name) =>
        FindInNamespace(compilation.GlobalNamespace, name);

    private static INamedTypeSymbol? FindInNamespace(INamespaceSymbol ns, string name)
    {
        foreach (var member in ns.GetMembers())
        {
            if (member is INamespaceSymbol childNs)
            {
                var found = FindInNamespace(childNs, name);
                if (found is not null)
                    return found;

                continue;
            }

            if (member is INamedTypeSymbol type && type.TypeKind == TypeKind.Interface && string.Equals(type.Name, name, StringComparison.OrdinalIgnoreCase))
                return type;
        }
        return null;
    }
}
